apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: web-app
        image: us-central1-docker.pkg.dev/hot-cold-drp/app-repo/web-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"80": {"name": "http"}}}'
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
