name: Deploy Secondary Region

on:
  repository_dispatch:
    types: [failover_trigger]
  workflow_dispatch:

env:
  PROJECT_ID: hot-cold-drp
  SECONDARY_REGION: us-west1
  CLUSTER_NAME: gke-secondary-cluster

jobs:
  deploy-secondary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: 'gke-gcloud-auth-plugin'
    
    - name: Deploy Secondary Infrastructure
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        terraform init
        terraform apply -var="deploy_secondary=true" -auto-approve
        
        # Update Cloud Function with GitHub token
        gcloud functions deploy failover-trigger \
          --set-env-vars GH_PAT="$GH_PAT" \
          --region=us-central1 --project=hot-cold-drp
    
    - name: Configure Docker
      run: gcloud auth configure-docker us-west1-docker.pkg.dev
    
    - name: Get Secondary GKE Credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
          --region=$SECONDARY_REGION --project=$PROJECT_ID
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    
    - name: Deploy App to Secondary
      env:
        USE_GKE_GCLOUD_AUTH_PLUGIN: True
      run: |
        kubectl apply -f k8s/app.yaml
        kubectl rollout status deployment/web-app --timeout=300s
    
    - name: Add Secondary Endpoints to NEGs
      run: |
        chmod +x scripts/add-secondary-endpoints.sh
        ./scripts/add-secondary-endpoints.sh
    
    - name: Switch Load Balancer to Secondary
      run: |
        chmod +x scripts/switch-to-secondary.sh
        ./scripts/switch-to-secondary.sh