name: Test Failover

on:
  workflow_dispatch:

env:
  PROJECT_ID: hot-cold-drp
  REGION: us-central1
  CLUSTER_NAME: gke-primary-cluster

jobs:
  test-failover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: 'gke-gcloud-auth-plugin'
    
    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
          --region=$REGION --project=$PROJECT_ID
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    
    - name: Simulate Primary Failure
      env:
        USE_GKE_GCLOUD_AUTH_PLUGIN: True
      run: |
        echo "Scaling down primary application to simulate failure..."
        kubectl scale deployment web-app --replicas=0
        
        echo "Primary application scaled down - failover should trigger automatically"
        echo "Monitor alerts: https://console.cloud.google.com/monitoring/alerting"